name = "tfa-frontend"
compatibility_date = "2025-02-20"

[build]
command = "npm run build && npm run export" 
cwd = "./"

[site]
bucket = "./out" 

[env.production]
pages_build_output_dir = "./out" 

[env.preview]
pages_build_output_dir = "./out"
